version: "3"
services:
  mongo:
    image: mongo
    container_name: stock_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: stock
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
      - ./.docker/mongo/:/docker-entrypoint-initdb.d/
  mongo-express:
    image: mongo-express
    container_name: stock_mongo_exp
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongo:27017/
    ports:
      - 9876:8081
    depends_on: 
      - mongo